### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by szepeviktor** [inpsyde/WP-Stash#5]
@Biont After making nice fixes like
https://github.com/inpsyde/WP-Stash/blob/master/inc/WpCliCommand.php#L53
could you make a new release?

**Comment by Biont** [comment]
Yes. I was waiting for feedback on #1 but a release is overdue. As mentioned in the other issue, I am currently on vacation, but I should be able to take care of everything next week

**Comment by szepeviktor** [comment]
Thank you.
Have a nice day!
