### ISSUE TITLE
WPStash - Configuration via env var

### ISSUE THREAD

**Issue by Chrico** [inpsyde/WP-Stash#9]
Currently WPStash is listening in  `Inpsyde\WpStash\Config`  only to constants via `defined()`. In some scenarios this might not match because the configration happens via env vars. therefore there should be first of all a check in `Inpsyde\WpStash::fromConfig()` if the var is either `defined` or via `getenv` available and depending on that the config generated and also there's a duplication for generating the Config in `Inpsyde\WpStash::fromConfig()` and ``Inpsyde\WpStash::getDriver()`.

**Comment by Biont** [comment]
Implemented by #10
